### ISSUE TITLE
Eagle say brd files are not Eagle file

### ISSUE THREAD

**Issue by Wayne91** [adafruit/Adafruit-OLED-FeatherWing-PCB#1]
When attempting to open the *.brd file I get the following error in Eagle:

>  Error:
> 
> line 6, column 56: This is not an EAGLE file.

Any idea why this is happening?

**Comment by ladyada** [comment]
dunno, just checked by downloading zip and it works.

**Comment by Wayne91** [comment]
I'm using Eagle 7.6.0 light...?
Couldn't open the brd in solidworks either.
Clearly a problem on my end, if you were able to open it.
