### ISSUE TITLE
Not the recent version.

### ISSUE THREAD

**Issue by vogt31337** [adafruit/Adafruit-OLED-FeatherWing-PCB#3]
Hi,

As stated here [Issue somewhere else](https://github.com/adafruit/Adafruit_CircuitPython_SSD1306/issues/7#issuecomment-355622748), the board has been updated. Some picture show the new version, recognizable by a three legged transistor-thing right next to the reset button. 
But the new schematics are nowhere to be found. Only for the old version which has a diode at that spot.

Was this just a package change (three legged diode?) or as stated in the other Issue "a little resetter chip"? And how do I interface it? 

Because shutting off the display and trying to turn it on only works with a hard reset...

**Comment by kattni** [comment]
Hello! We've updated the PCB files in this repo to the current version, as well as the schematic on the associated Learn guide.
