### ISSUE TITLE
128x64 - Incorrect Button Labels

### ISSUE THREAD

**Issue by nicholaswilde** [adafruit/Adafruit-OLED-FeatherWing-PCB#5]
On the 128x64 OLED, comparing the button labels (A, B, & C) with the pin labels, they seems to be inconsistent. Button B is correct but buttons A & C are flipped. Button A is mapped to pin C (21 J) and Button C is mapped to pin A (19 H).

This has been confirmed by testing the physical OELD screen as well as looking at the schematics.

**Comment by ladyada** [comment]
yes this is documented here
https://learn.adafruit.com/adafruit-128x64-oled-featherwing/pinouts#optional-buttons-3071174-9

**Comment by nicholaswilde** [comment]
Bah, I should have read the docs. Thanks for the response and the hard work.

**Comment by ladyada** [comment]
all good, we'll fix on the next PCB order :)
