### ISSUE TITLE
Excessive fragility of the oled panel and proposition

### ISSUE THREAD

**Issue by bricox54** [adafruit/Adafruit-OLED-FeatherWing-PCB#6]
Hello,
The upper glass of the oled panel is cantilevered, on the side of pcb flex.
The simple fact of holding the card in my hands caused a crack visible only with the binocular, which made me lose several days of diagnostics.
The other manufacturers, after self-gluing the panel, deposit resin between the pcb and the upper glass, especially in the corners.

**Comment by ladyada** [comment]
the glass does not overhang, and OLEDs are very delicate - we'll look at adding resin but it would not be instant as we dont have any kind of resin machine

**Comment by dombru54** [comment]
Hello Ladyada, 

Thank you for all your answers. 

I have been working with oled screens for several years. 
Your panel upper glass overhang of 3.3 mm compared to the lower glass to the flex side. 

I have a project to make a featherwing with PMW3901 (flowMotion) and VL53L0X (laser rangefinder) used in drones like "Flow Breakout Bitcraze" 
https://www.bitcraze.io/products/old-products/flow-breakout/ 
Can we collaborate on this project ? 

Sorry for my english, i'm a french engineer ... ;>) ... 


De: "ladyada" ***@***.***> 
À: "adafruit/Adafruit-OLED-FeatherWing-PCB" ***@***.***> 
Cc: "dombru54" ***@***.***>, "Author" ***@***.***> 
Envoyé: Vendredi 29 Juillet 2022 16:58:56 
Objet: Re: [adafruit/Adafruit-OLED-FeatherWing-PCB] Excessive fragility of the oled panel and proposition (Issue #6) 





the glass does not overhang, and OLEDs are very delicate - we'll look at adding resin but it would not be instant as we dont have any kind of resin machine
