### ISSUE TITLE
Erroneous serigraphy of the resolution of the panel

### ISSUE THREAD

**Issue by bricox54** [adafruit/Adafruit-OLED-FeatherWing-PCB#7]
Hello,
The serigraphy is 128x64 so landscape mode.
In fact, the native screen orientation is portrait.
The serigraphy should be 64x128.
I had to rewrite part of my driver in C.

**Comment by ladyada** [comment]
technically yes, but the orientation is rotated so visibility is in done as 128x64, this is not an error
