### ISSUE TITLE
I2C address embiguy serigraphy

### ISSUE THREAD

**Issue by bricox54** [adafruit/Adafruit-OLED-FeatherWing-PCB#8]
Hello,
The I2C address serigraphy is 0x3C.
This is valid is 7-bit MSB mode.
In some driver, the mode is 8 bits so it becomes double in hexadecimal i.e. (0x3C<<1)=0x78

**Comment by ladyada** [comment]
we use the 7-bit standard for indicating I2C addresses
https://learn.adafruit.com/i2c-addresses
